Energy guard boundaries for macOS update

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -176,12 +176,12 @@ jobs:
           pr-comment: true
 
       - name: Validate macOS energy values
-        if: ${{ contains(matrix.os, 'macos') }}
+        if: ${{ contains(matrix.os, 'macos-13') }}
         shell: bash
         run: |
           set -e
-          min=60
-          max=80
+          min=85
+          max=115
           total_energy=$(awk '{sum+=$1} END {print int(sum+0.5)}' /tmp/eco-ci/energy-total.txt)
           if [[ $total_energy -gt $min && $total_energy -lt $max ]]; then
             echo "Energy value $total_energy is in the expected range [$min, $max]."
@@ -189,6 +189,22 @@ jobs:
             echo "Energy value $total_energy is outside the expected range or not an integer [$min, $max]."
             exit 1
           fi
+
+      - name: Validate macOS energy values
+        if: ${{ contains(matrix.os, 'macos-14') }}
+        shell: bash
+        run: |
+          set -e
+          min=42
+          max=58
+          total_energy=$(awk '{sum+=$1} END {print int(sum+0.5)}' /tmp/eco-ci/energy-total.txt)
+          if [[ $total_energy -gt $min && $total_energy -lt $max ]]; then
+            echo "Energy value $total_energy is in the expected range [$min, $max]."
+          else # if total_energy is not int the check will fail silently. Thus else is our fallback
+            echo "Energy value $total_energy is outside the expected range or not an integer [$min, $max]."
+            exit 1
+          fi
+
 
       - name: Validate linux energy values
         if: ${{ !contains(matrix.os, 'macos') }}
